version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.2'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'docs'
      SPHINX_SOURCE_DIR: ''
      SPHINX_OUTPUT_DIR: '_build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'
      SPHINX_APIDOC_PACKAGE_PATH: '../src/rst2typst'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras'
      - task: 'docs:apidoc'
      - 'lefthook install'
  docs-build:
    desc: 'Build documentation to PDF file'
    cmds:
      - 'uv run rst2pseudoxml docs/index.rst docs/index.pxml'
      - 'uv run rst2typst --page-break-level=1 docs/index.rst docs/index.typ'
      - 'typst c docs/index.typ docs/index.pdf'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-extras' # To write out as lock-file
