version: '3'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras'
      - 'lefthook install'
  docs-build:
    desc: 'Build documentation to PDF file'
    cmds:
      - 'uv run rst2pseudoxml docs/index.rst docs/index.pxml'
      - 'uv run rst2typst --page-break-level=1 docs/index.rst docs/index.typ'
      - 'typst c docs/index.typ docs/index.pdf'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-extras' # To write out as lock-file
