version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.2'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'docs'
      SPHINX_SOURCE_DIR: ''
      SPHINX_OUTPUT_DIR: '_build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'
      SPHINX_APIDOC_PACKAGE_PATH: '../src/rst2typst'
  demo:
    taskfile: './demo/Taskfile.yaml'
    dir: './demo'
    vars:
      PDF_OUTPUT_DIR: '{{.ROOT_DIR}}/docs/_static'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras'
      - task: 'docs:apidoc'
      - 'lefthook install'
  build-docs:
    desc: 'Build full document for deployment'
    cmds:
      - task: 'docs:apidoc'
      - task: 'demo:build'
      - task: 'docs:build'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-extras' # To write out as lock-file
